version: 0.2

phases:
  build:
    commands:
      - echo timestart $CODEBUILD_START_TIME
      - ls
      - npm run lint
      - npm run build
      - npm run test:ci
reports:
  UnitTestReportsAgain:
    files:
      - "test-results.xml"
  CoverageTestReportsAgain:
    files:
      - "cobertura-coverage.xml"
    base-directory: "coverage/valhalla"
    file-format: "CoberturaXml"
artifacts:
  files:
    - "**/*"
  name: dev-$CODEBUILD_BUILD_NUMBER-$(date +%Y-%m-%d)-$CODEBUILD_START_TIME
  base-directory: dist
  secondary-artifacts:
    dev_build:
      files:
        - "**/*"
      base-directory: dist
    unit_test:
      files:
        - "test-results.xml"
    coverage:
      files:
        - "cobertura-coverage.xml"
      base-directory: "coverage/valhalla"
