version: 0.2

phases:
  build:
    commands:
      - echo timestart $CODEBUILD_START_TIME
      - npm ci
      - npm run lint
      - npm run build
      - npm run test:ci
artifacts:
  files:
    - "**/*"
  name: dev-$CODEBUILD_BUILD_NUMBER-$(date +%Y-%m-%d)-$CODEBUILD_START_TIME
  base-directory: dist
  secondary-artifacts:
    dev_build:
      files:
        - "**/*"
      base-directory: dist
